springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /user-service
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html   # 自定义路径，默认为"/swagger-ui/index.html"
server:
  port: 8090
